Develop GopherVault
ZnNr/GopherVault pull request #1
Opened 2024-06-11 19:15 UTC by ZnNr

2024-06-14 12:03 UTC, tmvrus requested changes
часто повторяется паттерн
```
	if err != nil {
		log.Printf("ошибка при выполнении запроса: %s", err.Error())
	}

	if resp.StatusCode() != http.StatusOK {
		log.Printf("код состояния не ОК: %s\n", resp.Status())
	}
```	
если случится ошибка (например сетевая) то код дойдет до условия, попробуем получить статус и случится паника, так как resty не во всех случаях инициализирует ответ.

вот такие конструкции тоже встречаются повсеместно и зашумляют код
```
	userName, _ := cmd.Flags().GetString("user")
	title, _ := cmd.Flags().GetString("title")
	content, _ := cmd.Flags().GetString("content")
	metadata, _ := cmd.Flags().GetString("metadata")
```
для них прям напрашивается какая-то хелпер-функция

вызовы log.Printf(resp.String()) выглядит странно, сложно сказать, что хотел разработчик - залогировать ответ или что-то показать пользователю

файлы больше 500 строк это прям издевательство какое-то, попробуй декомпозицию

куча самоочевидных бесполезных комментариев, непонятно для кого они

cmd/  максимально перегружен кодом, по сути это просто точка входа в приложение, но там чего только нет

2024-06-14 12:03 UTC, tmvrus commented on cmd/add_card.go
> +	fmt.Println(resp.String())
пакет fmt для лоигрования не предназначен

2024-06-14 12:03 UTC, tmvrus commented on cmd/get_card.go
> +	if resp.StatusCode() != http.StatusOK {
тоже самое

2024-06-14 12:03 UTC, tmvrus commented on cmd/add_credentials.go
> +	if resp.StatusCode() != http.StatusOK {
если на строке 65 будет ошибка, тот тут случится паника

2024-06-14 12:03 UTC, tmvrus commented on cmd/add_notes.go
> +	fmt.Println(resp.String())
логирование

2024-06-14 12:03 UTC, tmvrus commented on cmd/root.go
> +		os.Exit(1)
было бы полезно сказать пользователю что именно пошло не так перед завершением программы

2024-06-14 12:03 UTC, tmvrus commented on cmd/run.go
> +	return nil
довольно странный дизайн ф-и, с одной стороны можно вернуть ошибку, а с друго просто завершить приложение, может придерживаться какого-то одно похода

2024-06-14 12:03 UTC, tmvrus commented on cmd/update_credentials.go
> +	resp, err := sendUpdateCredentialsRequest(cfg, body)
странно что тут resty завернут в ф-ю а выше - нет

2024-06-14 12:03 UTC, tmvrus commented on db/migrations/000001_credentials.up.sql
> +                                           primary key (user_name, login)
довольно странный дизайн, с одной стороны есть serial однозначно идентифицирующий запись, с другой primary key (user_name, login), получается у пользователей могут быть разные име но одинаковые логины, и одинаковые имена и разные лоигны, зачем так?

2024-06-14 12:03 UTC, tmvrus commented on db/migrations/000003_notes.up.sql
> +                                     primary key (user_name, title)
а если я хочу два одинаковых заголовка но с разным содержанем то уже не получится, зачем такое ограничение?

2024-06-14 12:03 UTC, tmvrus commented on db/migrations/000004_cards.up.sql
> +                                     primary key (user_name, bank_name, number)
пользователю можно иметь только одну карту в одном банке? а если я хочу одну дебетовую, вторую кредитную и третью зарплатную? смысл ограничения непонятен

2024-06-14 12:03 UTC, tmvrus commented on internal/database/database.go
> +	c, err := aes.NewCipher([]byte(params.EncryptionKey))
а зачем базе данных что-то вообще знать про шифрование? у нее ведь другая задача - надежно хранить то что дали.

2024-06-14 12:03 UTC, tmvrus commented on internal/database/database.go
> +		// Если возникла ошибка при сохранении заметки, возвращаем ошибку с информацией
это довольно бесполезный комментарий)

2024-06-14 12:03 UTC, tmvrus commented on internal/database/database.go
> +	// Возвращаем nil (без ошибок), если заметка успешно сохранена
да и этот тоже

2024-06-14 12:03 UTC, tmvrus commented on internal/database/database.go
> +		_ = rows.Err()
некрасиво
ошибки надо хотя бы логировать, но можно почитать документацию этих методов и разобраться когда их стоит вызывать

2024-06-14 12:03 UTC, tmvrus commented on internal/database/database_test.go
файл такого размера эт прям максимально неудобно читать,уже ли там нельзя выделить разные кейсы?

2024-06-14 12:03 UTC, tmvrus commented on internal/handler/handlers.go
> +var jwtKey = []byte("my_secret_key")
а почему переменная а не константа?

2024-06-14 12:03 UTC, tmvrus commented on internal/handler/handlers.go
> +	if err = h.db.Login(ctx, user.Login, user.Password); err != nil {
снова какое-то странное поведение базы, она ведь хранить должна, доставать когда попросят, зачем она занимается каким-то логином?

2024-06-14 12:03 UTC, tmvrus commented on internal/handler/handlers.go
> +	ctx := context.Background()
максимально странно
зачем создавать новый контекст если в запросе уже есть готовый?

2024-06-14 12:03 UTC, tmvrus commented on internal/handler/handlers.go
> +	w.Header().Set("Content-Type", "application/json")
а есть другой тип контента?
если нет, может мидлварь сделать?
а то 13 раз в коде одно и тоже

2024-06-14 12:03 UTC, tmvrus commented on internal/handler/handlers.go
> +	if err := h.db.SaveCredentials(ctx, requestCredentials); err != nil {
вот первый раз встречается правильный глагол для базы

2024-06-14 12:03 UTC, tmvrus commented on internal/handler/handlers.go
> +	w.WriteHeader(http.StatusOK)
на самом деле это писать не обязательно, библиотека сама поставит этот статус если другого не было

2024-06-14 12:03 UTC, tmvrus commented on internal/handler/handlers.go
> +	cookies map[string]string
их хендлеров осуществляется конкурентный доступ к этому полю, что бы это было безопасно нужно использовать мьютекс

2024-06-17 21:00 UTC, ZnNr commented on internal/handler/handlers.go
> +	ctx := context.Background()
// Используем контекст из запроса
	ctx := r.Context()

2024-06-17 21:01 UTC, ZnNr commented on cmd/root.go
> +		os.Exit(1)
добавил логирование

2024-06-19 10:30 UTC, ZnNr commented on cmd/update_credentials.go
> +	resp, err := sendUpdateCredentialsRequest(cfg, body)
завернул в функцию везде

2024-06-19 11:35 UTC, ZnNr commented on internal/handler/handlers.go
> +	w.Header().Set("Content-Type", "application/json")
сделал мидлварь в роутере

2024-06-19 11:35 UTC, ZnNr commented on internal/handler/handlers.go
> +	w.WriteHeader(http.StatusOK)
убрал во всех обработчиках

2024-06-19 11:36 UTC, ZnNr commented on internal/handler/handlers.go
> +	cookies map[string]string
добавил мьютенксы

2024-06-19 11:36 UTC, ZnNr commented on internal/database/database_test.go
извиняюсь, но переписать тесты уже не успел

2024-06-19 11:36 UTC, ZnNr commented on internal/database/database.go
> +		_ = rows.Err()
добавил логирование

2024-06-19 11:36 UTC, ZnNr commented on internal/database/database.go
> +	// Возвращаем nil (без ошибок), если заметка успешно сохранена
убрал

2024-06-19 11:37 UTC, ZnNr commented on internal/database/database.go
> +		// Если возникла ошибка при сохранении заметки, возвращаем ошибку с информацией
убрвал

2024-06-19 11:37 UTC, ZnNr commented on internal/database/database.go
> +	c, err := aes.NewCipher([]byte(params.EncryptionKey))
не смог решить

2024-06-19 11:37 UTC, ZnNr commented on db/migrations/000004_cards.up.sql
> +                                     primary key (user_name, bank_name, number)
добавил корректировки

2024-06-19 11:37 UTC, ZnNr commented on db/migrations/000004_cards.up.sql
> +                                     primary key (user_name, bank_name, number)
cardType

2024-06-19 11:37 UTC, ZnNr commented on db/migrations/000003_notes.up.sql
> +                                     primary key (user_name, title)
откорректировал

2024-06-19 11:38 UTC, ZnNr commented on db/migrations/000001_credentials.up.sql
> +                                           primary key (user_name, login)
откорректировал

2024-06-19 11:38 UTC, ZnNr commented on cmd/run.go
> +	return nil
поправил замечание

2024-06-19 11:38 UTC, ZnNr commented on cmd/add_notes.go
> +	fmt.Println(resp.String())
исправил

2024-06-19 11:38 UTC, ZnNr commented on cmd/add_credentials.go
> +	if resp.StatusCode() != http.StatusOK {
исправил

2024-06-19 11:38 UTC, ZnNr commented on cmd/get_card.go
> +	if resp.StatusCode() != http.StatusOK {
исправил

2024-06-19 11:38 UTC, ZnNr commented on cmd/add_card.go
> +	fmt.Println(resp.String())
исправил

2024-06-19 11:39 UTC, ZnNr commented
В основном провел декомпозицию кода, убрал часто повторяющиеся патерны в отдельбные функции

2024-06-20 22:30 UTC, ZnNr commented
Починил тесты, теперь вроде всё работает

2024-06-25 11:18 UTC, merged